"""Словарь предметной области: перечисления и сущности."""

from ege_tutor.core.domain.attempt import (
    AnswerCheck,
    Attempt,
    AttemptMode,
    AttemptStatus,
    HintEvent,
    Verdict,
)
from ege_tutor.core.domain.catalog import AnswerKind, Catalog, ExamSpec, ExamSpecItem, Skill, Topic
from ege_tutor.core.domain.code import (
    CODE_VERDICT_LABELS,
    CodeRun,
    CodeVerdict,
    TaskTestCase,
)
from ege_tutor.core.domain.content import TaskSource, VerificationStatus
from ege_tutor.core.domain.imports import (
    ImportBatch,
    ImportBatchStatus,
    ImportIssue,
    ImportReport,
)
from ege_tutor.core.domain.mastery import (
    MISTAKE_CATEGORY_NAMES,
    ClassifiedBy,
    MasteryAggregate,
    MasteryRecord,
    MasterySnapshot,
    Mistake,
    MistakeCategory,
    MistakeDraft,
    MistakePattern,
    Prediction,
    ReviewItem,
    ReviewReason,
    SkillMastery,
)
from ege_tutor.core.domain.profile import DEFAULT_TARGET_SCORE, StudentProfile
from ege_tutor.core.domain.subject import Subject
from ege_tutor.core.domain.task import (
    HINT_LEVELS,
    PRACTICE_STATUSES,
    SOURCE_LABELS,
    AnswerType,
    Task,
    TaskAsset,
    TaskDraft,
    TaskHint,
)

__all__ = [
    "CODE_VERDICT_LABELS",
    "DEFAULT_TARGET_SCORE",
    "HINT_LEVELS",
    "MISTAKE_CATEGORY_NAMES",
    "PRACTICE_STATUSES",
    "SOURCE_LABELS",
    "AnswerCheck",
    "AnswerKind",
    "AnswerType",
    "Attempt",
    "AttemptMode",
    "AttemptStatus",
    "Catalog",
    "ClassifiedBy",
    "CodeRun",
    "CodeVerdict",
    "ExamSpec",
    "ExamSpecItem",
    "HintEvent",
    "ImportBatch",
    "ImportBatchStatus",
    "ImportIssue",
    "ImportReport",
    "MasteryAggregate",
    "MasteryRecord",
    "MasterySnapshot",
    "Mistake",
    "MistakeCategory",
    "MistakeDraft",
    "MistakePattern",
    "Prediction",
    "ReviewItem",
    "ReviewReason",
    "Skill",
    "SkillMastery",
    "StudentProfile",
    "Subject",
    "Task",
    "TaskAsset",
    "TaskDraft",
    "TaskHint",
    "TaskSource",
    "TaskTestCase",
    "Topic",
    "Verdict",
    "VerificationStatus",
]
